// Generated by CoffeeScript 1.7.1
(function() {
  var TYPES, bSearch, compare, data, delta, get_distance, handler, hi_idx, idx, lo_idx, match_three_as, matcher, probe, words, _ref, _ref1;

  TYPES = require('coffeenode-types');

  this.equality = function(data, probe_or_handler) {
    return (this._equality(data, probe_or_handler))[0];
  };

  this._equality = function(data, probe_or_handler) {

    /* With thx to http://googleresearch.blogspot.de/2006/06/extra-extra-read-all-about-it-nearly.html,
    http://www.dweebd.com/javascript/binary-search-an-array-in-javascript
     */
    var cmp, h, handler, hi_idx, lo_idx, mid_idx, mid_value, probe;
    lo_idx = 0;
    hi_idx = data.length - 1;
    if ((TYPES.type_of(probe_or_handler)) === 'function') {
      handler = probe_or_handler;
      h = handler;
    } else {
      probe = probe_or_handler;
      h = null;
      handler = (function(_this) {
        return function(value, idx) {
          if (probe === value) {
            return 0;
          }
          if (probe < value) {
            return -1;
          }
          return +1;
        };
      })(this);
    }
    while (lo_idx <= hi_idx) {
      mid_idx = Math.floor((lo_idx + hi_idx) / 2);
      mid_value = data[mid_idx];
      cmp = handler(mid_value, mid_idx);
      if (cmp === 0) {
        return [mid_idx, probe, h];
      }
      if (cmp < 0) {
        hi_idx = mid_idx - 1;
      } else {
        lo_idx = mid_idx + 1;
      }
    }
    return [null, probe, h];
  };

  this.interval = function(data, handler) {
    var hi_idx, last_idx, lo_idx, mid_idx, probe, type, _ref;
    if ((type = TYPES.type_of(handler)) !== 'function') {
      throw new Error("expected a function, got a " + type);
    }
    _ref = this._equality(data, handler), mid_idx = _ref[0], probe = _ref[1];
    if (mid_idx == null) {
      return [mid_idx, mid_idx];
    }
    lo_idx = mid_idx - 1;
    hi_idx = mid_idx + 1;
    last_idx = data.length - 2;
    while (true) {
      if (lo_idx - 1 < 0) {
        break;
      }
      if (lo_idx > last_idx) {
        break;
      }
      if ((handler(data[lo_idx], lo_idx)) !== 0) {
        break;
      }
      lo_idx -= 1;
    }
    while (true) {
      if (hi_idx - 1 < 0) {
        break;
      }
      if (hi_idx > last_idx) {
        break;
      }
      if ((handler(data[hi_idx], hi_idx)) !== 0) {
        break;
      }
      hi_idx += 1;
    }
    return [lo_idx + 1, hi_idx - 1];
  };

  this.closest = function(data, probe_or_handler) {
    var handler, hi_idx, lo_idx, mid_dst, mid_dsta, mid_idx, mid_value, min_dsta, min_idx, probe;
    lo_idx = 0;
    hi_idx = data.length - 1;
    min_idx = null;
    min_dsta = +Infinity;
    if ((TYPES.type_of(probe_or_handler)) === 'function') {
      handler = probe_or_handler;
    } else {
      probe = probe_or_handler;
      handler = (function(_this) {
        return function(value, idx) {
          return probe - value;
        };
      })(this);
    }
    while (lo_idx <= hi_idx) {
      mid_idx = Math.floor((lo_idx + hi_idx) / 2);
      mid_value = data[mid_idx];
      mid_dst = handler(mid_value, mid_idx);
      if (mid_dst === 0) {
        return mid_idx;
      }
      mid_dsta = Math.abs(mid_dst);
      if (min_dsta > mid_dsta) {
        min_dsta = mid_dsta;
        min_idx = mid_idx;
      }
      if (mid_dst < 0) {
        hi_idx = mid_idx - 1;
      } else {
        lo_idx = mid_idx + 1;
      }
    }
    return min_idx;
  };

  if (module.parent == null) {
    bSearch = this;
    data = [0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351, 378, 406, 435, 465, 496, 528, 561, 595, 630, 666, 703, 741, 780, 820, 861, 903, 946, 990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431];
    probe = 300;
    delta = 100;
    compare = function(value) {
      if ((probe - delta <= value && value <= probe + delta)) {
        return 0;
      }
      if (probe - delta < value) {
        return -1;
      }
      return +1;
    };
    idx = bSearch.equality(data, probe);
    console.log(idx, data[idx]);
    idx = bSearch.equality(data, compare);
    console.log(idx, data[idx]);
    _ref = bSearch.interval(data, compare), lo_idx = _ref[0], hi_idx = _ref[1];
    console.log([lo_idx, hi_idx], [data[lo_idx], data[hi_idx]]);
    probe = 300;
    idx = bSearch.closest(data, probe);
    console.log('>>>', probe, idx, data[idx]);
    probe = 1000;
    idx = bSearch.closest(data, probe);
    console.log('>>>', probe, idx, data[idx]);
    probe = 1000;
    handler = (function(_this) {
      return function(value, idx) {
        return value - probe;
      };
    })(this);
    idx = bSearch.closest(data, probe);
    console.log('>>>', probe, idx, data[idx]);
    probe = -120;
    idx = bSearch.closest(data, probe);
    console.log('>>>', probe, idx, data[idx]);
    probe = 4000;
    idx = bSearch.closest(data, probe);
    console.log('>>>', probe, idx, data[idx]);
    words = "abbatastic abracadabra fellah search canopy catalyst fad jaded alley tajmahal\nsupercalifragilisticexpialidocious ferocious pretty horse".split(/\s+/);
    matcher = /a/g;
    get_distance = function(a, b) {
      var count_a, count_b, _ref1, _ref2;
      count_a = ((_ref1 = a.match(matcher)) != null ? _ref1 : '').length;
      count_b = ((_ref2 = b.match(matcher)) != null ? _ref2 : '').length;
      return count_a - count_b;
    };
    match_three_as = function(word) {
      var _ref1;
      return 3 - ((_ref1 = word.match(matcher)) != null ? _ref1 : '').length;
    };
    words.sort(get_distance);
    idx = bSearch.equality(words, match_three_as);
    if (idx != null) {
      console.log(idx, words[idx]);
    } else {
      console.log('not found');
    }
    _ref1 = bSearch.interval(words, match_three_as), lo_idx = _ref1[0], hi_idx = _ref1[1];
    if (lo_idx != null) {
      console.log([lo_idx, hi_idx]);
      console.log([
        (function() {
          var _i, _results;
          _results = [];
          for (idx = _i = lo_idx; lo_idx <= hi_idx ? _i <= hi_idx : _i >= hi_idx; idx = lo_idx <= hi_idx ? ++_i : --_i) {
            _results.push(words[idx]);
          }
          return _results;
        })()
      ]);
      console.log(words);
    } else {
      console.log('not found');
    }
  }

}).call(this);
